config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :seeks 
  delete 'accept_seek/:id', as: 'accept_seek', to: 'seeks#accept'

  resources :games
  resources :seeklists
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' },
                     path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'static_pages#home'
  get '/lobby', to: 'static_pages#lobby'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seek.rb
class Seek < ApplicationRecord
  belongs_to :user
  belongs_to :seeklist

  validates :timecontrol, numericality: { greater_than: 0 }
  validate :user_confirmed?

  private

  def user_confirmed?
    errors.add(:user, 'must be confirmed.') unless user && user.confirmed?
  end
end

app/controllers/seeks_controller.rb
class SeeksController < ApplicationController
  def create
    @seek = Seek.new(seek_params)
    @seek.user = current_user
    # Store timecontrol in seconds in the databae
    @seek.timecontrol = (seek_params[:timecontrol].to_i * 60).floor
    if @seek.save
      # Seek should up broadcast right after creation
      ActionCable.server.broadcast 'seeks',
                                   action: 'add',
                                   seek: render_seek(@seek)
      head :ok
    else
      redirect_to lobby_url
    end
  end

  def destroy
    @seek = Seek.find params[:id]
    ActionCable.server.broadcast 'seeks',
                                 action: 'destroy',
                                 seek_id: @seek.id
    @seek.destroy
  end

  def accept
    @seek = Seek.find params[:id]
    white, black = [@seek.user, current_user].shuffle
    game_params = { white_user: white,  black_user:black, timecontrol: @seek.timecontrol }
    if @game = Game.create(game_params)
      Game.broadcast_start(white, black, game_url(@game))
      ActionCable.server.broadcast 'seeks',
                                   action: 'destroy',
                                   seek_id: @seek.id
      @seek.destroy
    else
      flash[:error] = 'Game could not be created.'
    end
  end

  private

  def render_seek(seek)
    render partial: 'seek', locals: { seek: seek }
  end

  def seek_params
    params.require(:seek).permit(:timecontrol, :seeklist_id)
  end
end

app/helpers/seeks_helper.rb
module SeeksHelper
end

app/views/seeks/_seek.html.erb
<tr class="seek" id= <%= "seek_#{seek.id}" %>>
  <td class="cancel">
    <% if seek.user == current_user %>
      <%= button_to '×', seek, method: :delete, remote: true %>
    <% end %>
  </td>
  <td class="seeker" %>
    <%= seek.user.handle %>
  </td>
  <td class="time-control">
    <%= (seek.timecontrol)/60 %>
  </td>
  <td>
    <% unless seek.user == current_user %>
      <%= button_to 'Accept', accept_seek_path(seek), method: :delete, remote: true %>
    <% end %>
  </td>
</tr>

app/views/seeks/_seek_form.html.erb
<h3 class='form-title'>Your Seek</h3>
<%= form_for seek, remote: true, authenticity_token: true do |f| %>
  <div class="time-control-field">
    <%= f.label :time_control %>
    <%= f.number_field :timecontrol, class: "form-control", data: {timecontrol: "seek"} %>
    MINS
  </div>
<%= f.hidden_field :seeklist_id, value: seeklist.id %>
<%= f.submit "Seek", class: "button", data: {send: "seek"} %>
<% end %>