config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :seeks 
  delete 'accept_seek/:id', as: 'accept_seek', to: 'seeks#accept'

  resources :games
  resources :seeklists
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' },
                     path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'static_pages#home'
  get '/lobby', to: 'static_pages#lobby'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_global_nav.html.erb
<nav class="global-navbar">
  <ul class="global-nav left">
    <li class="global-nav-item">
      <%= link_to 'Odin Chess', root_path, class: 'global-nav-link home' %>
    </li>
  </ul>
  <ul class="global-nav right">
    <% if user_signed_in? %>
      <li class="global-nav-item">
        <%= link_to 'Logout',
          destroy_user_session_path,
          class: 'global-nav-link login',
          method: :delete %>
      </li>
      <li class="global-nav-item">
        <%= link_to 'Lobby', lobby_path, class: 'global-nav-link signup' %>
      </li>
    <% else %>
      <li class="global-nav-item">
        <%= link_to 'Login',
          new_user_session_path,
          class: 'global-nav-link login' %>
      </li>
      <li class="global-nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'global-nav-link signup' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, messages| %>
  <% message_type = flash[:notice] ? 'info': message_type %>
  <% message_type = flash[:alert]  ? 'danger': message_type %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>

      <% messages = [messages] unless messages.kind_of?(Array) %>
      <% messages.each do |msg| %>
        <%= content_tag(:li, msg) %>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinChess</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/global_nav' %>
    <%= render 'layouts/messages' %>
    <div id="main-container">
      <%= yield %>
    </div>
    <%= insert_paloma_hook %>
  </body>
</html>